export const resMessage = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  USER_ACCOUNT_NOT_FOUND: "USER_ACCOUNT_NOT_FOUND",
  USER_FOUND: "USER_FOUND",
  USER_REGISTER: "USER_REGISTER",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  UPDATE_SUCCESS: "User updated successfully",
  FETCH_SUCCESS: "Users fetched successfully",

  PRODUCT_CREATED: "Product created successfully",
  PRODUCT_LIST_FETCHED: "Product list fetched successfully",
  PRODUCT_FETCHED: "Product fetched successfully",
  PRODUCT_UPDATED: "Product updated successfully",
  PRODUCT_DELETED: "Product deleted successfully",
  NOT_FOUND: "Product not found",
  ALREADY_EXISTS: "Product already exists",
  INTERNAL_SERVER_ERROR: "Something went wrong",
  PRODUCT_NOT_FOUND: "No products matched your search.",
  PRODUCT_FOUND: "Products found successfully.",
  NO_ORDERS: "No orders found.",
  NO_PRODUCT_IDS: "No product IDs found in orders.",
  POPULAR_PRODUCTS_FOUND: "Popular products fetched successfully.",
  POPULAR_PRODUCTS_NOT_FOUND: "No matching products found.",
  // SUBCATEGORY_CREATED: "Subcategory created successfully",
  // SUBCATEGORY_LIST_FETCHED: "Subcategory list fetched successfully",
  // SUBCATEGORY_FETCHED: "Subcategory fetched successfully",
  // SUBCATEGORY_UPDATED: "Subcategory updated successfully",
  // SUBCATEGORY_DELETED: "Subcategory deleted successfully",
  // NOT_FOUND: "Subcategory not found",
  // ALREADY_EXISTS: "Subcategory already exists",
  // INTERNAL_SERVER_ERROR: "Something went wrong",

  CATEGORY_CREATED: "Category created successfully.",
  CATEGORY_LIST_FETCHED: "Category list fetched successfully.",
  ORDER_PLACED: "Order placed successfully.",
  ORDER_LIST_FETCHED: "Orders retrieved successfully.",
  ORDER_FETCHED: "Order retrieved successfully.",
  ORDER_UPDATED: "Order updated successfully.",
  ORDER_NOT_FOUND: "Order not found.",
  NO_ORDERS_FOUND: "No orders found for the user.",
  // PRODUCT_CREATED: "Product created successfully.",
  // PRODUCT_LIST_FETCHED: "Product list fetched successfully.",
  // ORDER_PLACED: "Order placed successfully.",
  // ORDER_LIST_FETCHED: "Orders retrieved successfully.",
  // ORDER_FETCHED: "Order retrieved successfully.",
  // ORDER_UPDATED: "Order updated successfully.",
  // ORDER_NOT_FOUND: "Order not found.",
  // NO_ORDERS_FOUND: "No orders found for the user.",

  // ALREADY_EXISTS: "Category already exists.",
  // CATEGORY_CREATED: "Category created successfully.",
  // CATEGORY_LIST_FETCHED: "Categories fetched successfully.",
  // CATEGORY_NOT_FOUND: "Category not found.",
  // CATEGORY_FETCHED: "Category fetched successfully.",
  // CATEGORY_UPDATED: "Category updated successfully.",
  // CATEGORY_STATUS_UPDATED: "Category status updated successfully.",
  // INTERNAL_SERVER_ERROR:
  //   "Oops! Something went wrong. Our team is looking into it.",

  CATEGORY_CREATED: "Category created successfully.",
  CATEGORY_LIST_FETCHED: "Category list fetched successfully.",
  SUBCATEGORY_CREATED: "Sub-category created successfully.",
  SUBCATEGORY_LIST_FETCHED: "Sub-category list fetched successfully.",
  ALREADY_EXISTS: "This item already exists.",
  INTERNAL_SERVER_ERROR: "Something went wrong. Please try again later.",
  ACTION_COMPLETE: "Action completed successfully.",

  CART_UPDATED: "Cart updated successfully.",
  CART_CREATED: "Cart created successfully.",
  CART_FETCHED: "Cart fetched successfully.",
  NO_CART_FOUND: "No cart found.",
  CART_NOT_FOUND: "Cart not found.",
  PRODUCT_NOT_FOUND: "Product not found in cart.",
  CART_ITEM_UPDATED: "Cart item updated successfully.",
  CART_ITEM_DELETED: "Cart item deleted successfully.",
  INTERNAL_SERVER_ERROR:
    "Oops! Something went wrong. Our team is looking into it.",

  WISHLIST_ADDED: "Product added to wishlist",
  WISHLIST_FETCHED: "Wishlist fetched successfully",
  NO_WISHLIST_FOUND: "Wishlist not found",
  PRODUCT_NOT_IN_WISHLIST: "Product not found in wishlist",
  WISHLIST_ITEM_REMOVED: "Product marked as deleted from wishlist",
  INTERNAL_SERVER_ERROR:
    "Oops! Something went wrong. Our team is looking into it.",

  MEDIA_UPLOADED: "Media uploaded successfully.",
  MEDIA_RETRIEVED: "Media retrieved successfully.",
  NO_MEDIA_FOUND: "No media found.",
  MEDIA_DELETED: "Media deleted successfully.",
  MEDIA_UPDATED: "Media updated successfully.",
  VIDEO_ADDED: "Video URL added successfully.",
  SOCIAL_LINKS_CREATED: "Social links created successfully.",
  SOCIAL_LINKS_UPDATED: "Social links updated successfully.",
  SOCIAL_LINKS_RETRIEVED: "Social links retrieved successfully.",
  NO_SOCIAL_LINKS_FOUND: "No social links found.",
  INTERNAL_SERVER_ERROR:
    "Oops! Something went wrong. Our team is looking into it.",
  ALREADY_EXISTS: "Category already exists.",
  CATEGORY_CREATED: "Category created successfully.",
  CATEGORY_LIST_FETCHED: "Category list fetched successfully.",

  BANNER_CREATED: "Banner created successfully",
  BANNER_LIST_FETCHED: "Banner list fetched successfully",
  BANNER_LIST_EMPTY: "No banners found",
  BANNER_DELETED: "Banner deleted successfully",
  BANNER_STATUS_UPDATED: "Banner status updated successfully",
  INTERNAL_SERVER_ERROR: "Oops! Something went wrong. Please try again later.",
  ALREADY_EXISTS: "Already exists",
  CATEGORY_CREATED: "Category created successfully",
  CATEGORY_LIST_FETCHED: "Category list fetched successfully",

};

export const resStatusCode = {
  ACTION_COMPLETE: 200,
  CLIENT_ERROR: 400,
  INTERNAL_SERVER_ERROR: 500,
  CONFLICT: 409,
  UNAUTHORISED: 401,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
};
